export const names =[
    {name: 'NITA KOIRALA', code: 'NK'},
    {name: 'NITESH KHATIWODA', code: 'NK'},
    {name: 'OMPRAKASH UPADHAYAY', code: 'OU'},
    {name: 'PALISTHA SINGH', code: 'PS'},
    {name: 'PRAMILA KHADKA', code: 'PK'},
    {name: 'PUJA POUDEL KHATRI', code: 'PPk'},
    {name: 'RAJENDRA SODARI', code: 'RS'},
    {name: 'RAMESH PANDEY', code: 'RP'},
    {name: 'RASKIN SHRESTHA', code: 'RS'},
    {name: 'ROJINA GHIMIRE', code: 'RG'},
    {name: 'ROSY DAHAL', code: 'RD'},
    {name: 'SABINA ADHIKARI', code: 'SA'},
    {name: 'SADAN BHATTARAI', code: 'SB'},
    {name: 'SAMEER RAJ JOSHI', code: 'SRJ'},
    {name: 'SAMIR KATTEL', code: 'SK'},
    {name: 'SANDESH BHETWAL', code: 'SB'},
    {name: 'SANJAY MANADHAR', code: 'SM'},
    {name: 'SANJEEV KHADKA', code: 'SK'},
    {name: 'SANTOSH SHAH', code: 'SS'},
    {name: 'SAYAL SHARADA MADHIKARMY', code: 'SSM'},
    {name: 'SHARAD SHRESTHA', code: 'SS'},
    {name: 'SHARMILA THAPA MAGAR', code: 'STM'},
    {name: 'SIMA YADAV', code: 'SY'},
    {name: 'SMRITY PULAMI', code: 'SP'},
    {name: 'SUBASH TIMALSINA', code: 'ST'},
    {name: 'UDAYA CHANDRA PRAJAPATI', code: 'UCP'},
]